# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e4c9a6013876bd59b8223f357ed095392664edadd9d125507bb7964ed1875a13732214d4e79a63a87a9b0a30dfb0e3fe78b7b34a1fba567dbe43cb8c1b7674e

test:
  secret_key_base: c4d49488ea90dfe2d1742d1f9f1a2a25babef68536430fa415ce55b67865dbf0f26991cc620eb7098fbaf3efe2c7951765b7d204e528e215e88f6d6b0dceada8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
